### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by MrSirKingLord** [haliphax/tts#2]
peter@peter-pc:~/.local/src/tts$ sudo docker-compose build
nginx uses an image, skipping
Building engine
Sending build context to Docker daemon  245.8kB
Error response from daemon: dockerfile parse error line 7: unknown instruction: SET
ERROR: Service 'engine' failed to build : Build failed

OS: LMDE 6 (faye) x86_64
Kernel: 6.1.0-13-amd64

**Comment by haliphax** [comment]
What version of docker are you using? Seems like it's not properly parsing this option for the HEREDOC style blocks:

```
# syntax = docker/dockerfile-upstream:1-labs
```

**Comment by MrSirKingLord** [comment]
Thanks, I did have outdated docker from Debian 12 APT repo. Needed Docker APT repo

```
Debian 12: docker.io/stable,now 20.10.24+dfsg1-1+b3 amd64 
Docker Repo: docker-ce/bookworm,now 5:24.0.7-1~debian.12~bookworm amd64 [installed]
```
